### ISSUE TITLE
May not work in mavericks

### ISSUE THREAD

**Issue by ChristopherA** [joelcarranza/particular-pinboard#3]
I heard good things about the bookmarklet, forked it, downloaded it on a new mavericks system, installed brew, node and uglify.js, however, the build files are blank. I suspect a problem with the script in mavericks. I'm not a shell expert so I'm not sure what is wrong, but my guess is uglify-js isn't quite right.

**Comment by ChristopherA** [comment]
Can you just make your build folder available in the git archive?

**Comment by joelcarranza** [comment]
I don't have mavericks installed (yet) and have not been able to test the build process. You should make sure that `uglifyjs` is on your path when you run the build script. The easiest way to do this is to install it [globally](http://blog.nodejs.org/2011/03/23/npm-1-0-global-vs-local-installation/) by running:

```
npm install uglifyjs -g
```

**Comment by ChristopherA** [comment]
On Wed, Nov 20, 2013 at 8:30 AM, Joel Carranza notifications@github.comwrote:

> npm install uglifyjs -g

No, that didn't work either.

I don't get any errors from the script, but the build files, like
bookmark.js are all:

javascript:

Any chance you can make your build files available in github?

-- Christopher Allen

**Comment by redzep** [comment]
I too had heard excellent things about this bookmarklet, and am soooo close to getting it installed. Forgive my ignorance, but I can't get it to recognize uglifyjs... Installed it globally as per your suggestion, but it keeps "bailing" The uzipped folder "particular-pinboard-master" and node_modules folder (which contains the uglify-js folder) are both at the root level of my administrator folder. Mac OS X 10.9.1

Here's what I get:

Manobook2013:particular-pinboard-master mano-macbook$ npm install uglifyjs -g
npm http GET https://registry.npmjs.org/uglifyjs
npm http 304 https://registry.npmjs.org/uglifyjs
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/amdefine
uglifyjs@2.3.6 /usr/local/lib/node_modules/uglifyjs
├── async@0.2.9
├── optimist@0.3.7 (wordwrap@0.0.2)
└── source-map@0.1.31 (amdefine@0.1.0)
Manobook2013:particular-pinboard-master mano-macbook$ /Users/mano-macbook/particular-pinboard-master/build.sh 
No uglifyjs found. Bailing out
Manobook2013:particular-pinboard-master mano-macbook$

**Comment by redzep** [comment]
my brother helped me solve it: Nodes > Uglify needs to be inside the particular pinboard folder

**Comment by joelcarranza** [comment]
Awesome - glad to hear it. I haven’t upgraded to Mavericks yet but when I do i will update particular-pinboard with anything I can find

—Joel

**Comment by tupton** [comment]
You need to install uglifyjs with `npm install uglify-js` – note the "-". I don't know what the difference is between the two, but the one with the dash includes the binary that you need to build this bookmarklet.

**Comment by joelcarranza** [comment]
I'm closing this out as I believe tupton has correctly identified the point of confusion. I've added a mention in the README

**Comment by christophersutton** [comment]
I seem to be having the same issues that Christopher A was originally having - I'm not getting any errors but the output files are blank (other than "javascript:"). I've checked that I've installed uglify-js (with the dash).

**Comment by tupton** [comment]
@christophersutton how did you install `uglify-js`? What are the contents of `/path/to/particular-pinboard/node_modules/uglify-js`? What about the output of `which uglifyjs`? And lastly, have you seen #9?

And just in case `uglify-js` isn't the problem, how are you building the bookmarklets?
