### ISSUE TITLE
"Request URI is too long" on pages with long description

### ISSUE THREAD

**Issue by stanislavshabalin** [joelcarranza/particular-pinboard#5]
Example: http://video.yandex.ru/users/ya-events/view/430/
Generated url: <pre>https://pinboard.in/add?showtags=yes&url=http%3A%2F%2Fvideo.yandex.ru%2Fusers%2Fya-events%2Fview%2F430%2F%3Fcauthor%3Dya-events%26cid%3D48&title=Как%20мы%20делаем%20панорамы%20улиц%20—%20Максим%20Хохлов&description=Яндекс.Карты%20—%20третий%20по%20популярности%20сервис%20Яндекса.%20Мы%20помогаем%20пользователю%20сориентироваться%20на%20местности%20и%20отвечаем%20на%20вопросы%20«Как%20это%20выглядит%3F»%2C%20«Как%20пройти%20или%20доехать%3F»%2C%20«Что%20есть%20вокруг%3F».%20Для%20этого%20у%20нас%20есть%20схемы%2C%20спутниковые%20фотографии%2C%20народная%20карта%2C%20панорамы%20улиц%20и%20фотографии%20домов.%20В%20июне%202011%20года%20мы%20запустили%20панорамы%20улиц%20в%20Астане.%20Релиз%20панорам%20улиц%20в%20каждом%20новом%20городе%20—%20довольно%20сложный%20технологический%20процесс.%20Он%20включает%20в%20себя%20такие%20этапы%20как%3A%20предварительная%20разметка%20карт%2C%20съёмка%20изображений%20с%20записью%20gps%5C-координат%2C%20«склейка»%20панорамных%20изображений%2C%20подготовка%20и%20обработка%20фотографий%20и%20данных%20и%2C%20в%20итоге%2C%20их%20публикация%20на%20сервисе.%20Более%20детально%20в%20докладе%20пойдет%20речь%20об%20основных%20этапах%20внутренней%20кухни%20сервиса%20панорамы%20улиц.&tags=</pre>

**Comment by stanislavshabalin** [comment]
Better example: http://blogs.atlassian.com/2014/01/simple-git-workflow-simple/

**Comment by stanislavshabalin** [comment]
And another one: http://www.productivityist.com/blog/using-drafts-and-launch-center-pro

**Comment by tupton** [comment]
Another example: http://www.overthought.org/blog/2014/the-ultimate-guide-to-solving-ios-battery-drain

**Comment by joelcarranza** [comment]
This should be fixed now. Thanks tupton!
